steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: amdx86/alpinelinuxtest
      tags: v1
      dockerfile: dockerfiles
